--JUNÇÃO DA TABELA CLIENTE COM LABORATORIOS
SELECT C.NOME_CLIENTE, L.TIPO_LAB, A.DATA
FROM AGENDA A
INNER JOIN CLIENTES C
ON C.id_cliente = A.id_cliente
INNER JOIN LABORATORIOS L
ON A.ID_LAB = L.ID_LAB
ORDER BY A.DATA,C.NOME_CLIENTE